version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bank_postgres
    environment:
      POSTGRES_DB: bank_rest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bank_app:
    image: openjdk:21-jdk
    container_name: bank_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bank_rest
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGELOG: classpath:db/migration/change-log.yaml
      SPRING_APPLICATION_NAME: bank_rest
      SERVER_PORT: 8080
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - ./target/bank_rest.jar:/app/bank_rest.jar
    command: ["java", "-jar", "/app/bank_rest.jar"]
volumes:
  pgdata:
