spring:
  liquibase:
    enabled: ${LIQUIBASE_ENABLED:true}
    change-log: ${LIQUIBASE_CHANGE_LOG:classpath:/db/migration/change-log.yaml}
  application:
    name: ${APPLICATION_NAME:bank_rest}
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/bank_rest}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${DATASOURCE_DRIVER:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_HIBERNATE_DDL_AUTO:update}

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY:bb881451354ad90b161deb433b52a964ec4cd34db010d24f3e116136ab734e8a}
    access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:900000}
    refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}

server:
  port: ${SERVER_PORT:8080}

springdoc:
  swagger-ui:
    url: ${SWAGGER_URL:docs/openapi.yml}
    path: ${SWAGGER_PATH:swagger-ui.html}
